version: "3.8"

services:
  db: 
    image: postgres:17.4
    container_name: paytm_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: amitaarav
      POSTGRES_DB: mhoneydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    
volumes:
  postgres_data:
