name: Build Succeed on PR

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Build the project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '>=18'

            - name: Install dependencies
              run: npm install

            - name: generate prisma client
              run: npm run db:generate

            - name: Build
              run: npm run build